# Change these first
owner: itsyuni # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Landing about me – yuni.su
    url: https://yuni.su
  - name: Home dedicated Raspberry Pi 3 + home network center
    url: https://rpi.yuni.su
  - name: Paralone Media – Landing
    url: https://paralonemedia.com
  - name: Paralone Media – Workspace for artists
    url: https://my.paralonemedia.com
  - name: Paralone Media – API Workspace
    url: https://api.paralonemedia.com



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yuni.su
  # baseUrl: /your-repo-name
  logoUrl: 
  name: yuni Status
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
